### ISSUE TITLE
Can't access connection in Google Colab

### ISSUE THREAD

**Issue by mercy-thuyle** [donydchen/FMPN-FER#10]
Hello,
I have some problem with the first script and here are the traceback.
![image](https://user-images.githubusercontent.com/62128227/135709247-b88aee8e-ae28-464d-923f-a631eb879845.png)

I wonder that did I run in google colab is right? Or I have to run local in pycharm or jupyter notebook?

**Comment by donydchen** [comment]
Sorry but I didn't try this project on Google Colab, and I didn't try it with Jupiter notebook either. My suggestion is to run this project directly on a Ubuntu server. Hope it help.

**Comment by mercy-thuyle** [comment]
Thank you so much.
