### ISSUE TITLE
what is the purpose of PFN? what about two seperate CNN feature extractor and and feature ensembling?  

### ISSUE THREAD

**Issue by karthikeyan2ai** [donydchen/FMPN-FER#3]

**Comment by donydchen** [comment]
Hi @karthikeyan2ai , thanks for your interest in our work. 
As per our paper, 
> Prior   Fusion   Net   (PFN) is  designed  to  automatically fuse  the  original  input  face  with  the  face  that  is  masked  by the  facial-motion  mask  learned  from  FMG.  The  former  is to  provide  holistic  features,  while  the  latter  emphasizes  the moving areas, which reflects the common expression definition and  domain  knowledge.

**Comment by karthikeyan2ai** [comment]
why cant we avoid fusing and train two CNN feature extractor for generated mask and face image separately and then classifier on combined features? what is advantage of single CNN feature extractor on fused image?

**Comment by karthikeyan2ai** [comment]
> Hi @karthikeyan2ai , thanks for your interest in our work.
> As per our paper,
> 
> > Prior   Fusion   Net   (PFN) is  designed  to  automatically fuse  the  original  input  face  with  the  face  that  is  masked  by the  facial-motion  mask  learned  from  FMG.  The  former  is to  provide  holistic  features,  while  the  latter  emphasizes  the moving areas, which reflects the common expression definition and  domain  knowledge.

Thanks for the quick response :)

**Comment by donydchen** [comment]
Sure it is ok to just use a single branch, but it may lead to the degradation of performance. 
Please note that this work is a research project, we are more interested in exploring how to boost the performance. And we figure out that by integrating the domain knowledge, facial motion prior, into the network using an additional branch, the extracted features become more robust and thus lead to the improvement of performance.
It depends, my suggestions are, 
* If you are working on a research project, you can go with an additional branch, which may get better performance, especially on facial expression benchmark datasets, but an additional branch will also bring some more computation cost. 
* If you are working on an engineer project, and the project is very sensitive to memory and computation cost, sure you can directly train a single branch, e.g. VGG, with related datasets that contain as more images as possible. 
Hope it help.

**Comment by karthikeyan2ai** [comment]
Thanks :)
